/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBEntities.GamePlayInfo;
import DBModels.GamePlayInfoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author BuuBuu
 */
public class CuaHangGem extends javax.swing.JFrame implements ActionListener {
String username ="AAA";
      ArrayList<GamePlayInfo> gameinfo;
    public CuaHangGem() {
        initComponents();
        this.btnCombo1.addActionListener(this);
        this.btnCombo2.addActionListener(this);
        this.btnCombo3.addActionListener(this);
        this.btnCombo4.addActionListener(this);
        this.btnCombo5.addActionListener(this);
        this.btnCombo6.addActionListener(this);
        showgem();
        
    }
public void showgem(){
    gameinfo = new GamePlayInfoDAO().getList();
    for(GamePlayInfo item: gameinfo){
        if(item.getPlayerID().equals(username)){
            txtGem.setText(String.valueOf(item.getPlayerGem()));
            txtname.setText(item.getPlayerID());
            break;
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnCombo4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCombo5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnCombo1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnCombo2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnCombo3 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnCombo6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtname = new javax.swing.JLabel();
        txtGem = new javax.swing.JLabel();
        gems = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bntNaptheABK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Online_Store_80px_1.png"))); // NOI18N
        jLabel1.setText("Cửa Hàng Gem");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 396, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 440));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Combo4: 300 Gem = $599,000 VND");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnCombo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gems_5.jpg"))); // NOI18N
        btnCombo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCombo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(btnCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(btnCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, 307, 246));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(280, 0));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Combo5: 450 Gem = $899,000 VND");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnCombo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gems_5.jpg"))); // NOI18N
        btnCombo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCombo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombo5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(btnCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(btnCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 331, 307, 246));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(900, 440));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Combo1: 30 Gem = $69,000 VND");

        btnCombo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/KimCuongBase225.JPG"))); // NOI18N
        btnCombo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btnCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 106, 307, 218));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(280, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCombo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/KCcombo1_1.JPG"))); // NOI18N
        btnCombo2.setMaximumSize(new java.awt.Dimension(303, 233));
        btnCombo2.setMinimumSize(new java.awt.Dimension(303, 233));
        btnCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombo2ActionPerformed(evt);
            }
        });
        jPanel10.add(btnCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 13, 222, 170));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Combo2: 70 Gem = $149,000 VND");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 235, 24));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 106, 307, 218));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setToolTipText("");
        jPanel11.setPreferredSize(new java.awt.Dimension(280, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Combo3: 150 Gem = $329,000 VND");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 188, 249, -1));

        btnCombo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/KCcombo3225.JPG"))); // NOI18N
        btnCombo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCombo3.setMaximumSize(new java.awt.Dimension(303, 233));
        btnCombo3.setMinimumSize(new java.awt.Dimension(303, 233));
        jPanel11.add(btnCombo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 0, 214, 181));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 106, 307, 218));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(280, 0));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Combo6: 600 Gem = 1,199,000 VND");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnCombo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gems_5.jpg"))); // NOI18N
        btnCombo6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCombo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 331, 307, 249));

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setText("BLUEN NGUYEN");
        jPanel3.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 160, -1));

        txtGem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGem.setForeground(new java.awt.Color(255, 255, 255));
        txtGem.setText("234");
        jPanel3.add(txtGem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 60, -1));

        gems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S7.png"))); // NOI18N
        jPanel3.add(gems, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_undo_80px_2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 70, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unnamed300_80px.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 575, -1));

        bntNaptheABK.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bntNaptheABK.setText("Nạp thẻ ABK");
        bntNaptheABK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNaptheABKActionPerformed(evt);
            }
        });
        jPanel1.add(bntNaptheABK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCombo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombo6ActionPerformed

    private void btnCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombo1ActionPerformed

    private void btnCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombo2ActionPerformed

    private void btnCombo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombo4ActionPerformed

    private void btnCombo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombo5ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void bntNaptheABKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNaptheABKActionPerformed
        // TODO add your handling code here:
        STore st = new STore(this, rootPaneCheckingEnabled);
         st.setVisible(true);
    }//GEN-LAST:event_bntNaptheABKActionPerformed
 
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuaHangGem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuaHangGem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuaHangGem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuaHangGem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuaHangGem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNaptheABK;
    private javax.swing.JButton btnCombo1;
    private javax.swing.JButton btnCombo2;
    private javax.swing.JButton btnCombo3;
    private javax.swing.JButton btnCombo4;
    private javax.swing.JButton btnCombo5;
    private javax.swing.JButton btnCombo6;
    private javax.swing.JLabel gems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel txtGem;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables

//   public void check(){
//               if (e.getSource() == this.btnCombo1) {
//            pmCombo1confirm cf1 = new pmCombo1confirm();
//            cf1.setVisible(true);
//        } else if (e.getSource() == this.btnCombo2) {
//            pmCombo2confirm cf2 = new pmCombo2confirm();
//            cf2.setVisible(true);
//        } else if (e.getSource() == this.btnCombo3) {
//            pmCombo3confirm cf3 = new pmCombo3confirm();
//            cf3.setVisible(true);
//        } else if (e.getSource() == this.btnCombo4) {
//            pmCombo4confirm cf4 = new pmCombo4confirm();
//            cf4.setVisible(true);
//        } else if (e.getSource() == this.btnCombo5) {
//            pmCombo5confirm cf5 = new pmCombo5confirm();
//            cf5.setVisible(true);
//        } else if (e.getSource() == this.btnCombo6) {
//            pmCombo6confirm cf6 = new pmCombo6confirm();
//            cf6.setVisible(true);
//        }
//   }
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.btnCombo1) {
            pmCombo1confirm cf1 = new pmCombo1confirm();
            cf1.setVisible(true);
        } else if (e.getSource() == this.btnCombo2) {
            pmCombo2confirm cf2 = new pmCombo2confirm();
            cf2.setVisible(true);
        } else if (e.getSource() == this.btnCombo3) {
            pmCombo3confirm cf3 = new pmCombo3confirm();
            cf3.setVisible(true);
        } else if (e.getSource() == this.btnCombo4) {
            pmCombo4confirm cf4 = new pmCombo4confirm();
            cf4.setVisible(true);
        } else if (e.getSource() == this.btnCombo5) {
            pmCombo5confirm cf5 = new pmCombo5confirm();
            cf5.setVisible(true);
        } else if (e.getSource() == this.btnCombo6) {
            pmCombo6confirm cf6 = new pmCombo6confirm();
            cf6.setVisible(true);
        }
        
       
          
    }
    }

